-- =============================================================================
-- Denial Appeal Pro — Phase A: initial Supabase schema (single migration)
-- =============================================================================
-- Reconciled from:
--   1) backend/models.py (primary column definitions)
--   2) All backend/migrate_*.py additive changes (acquisition, retention, denial
--      queue, usage tracking, tracking columns, claim recovery, batch jobs,
--      coding intelligence, intelligence snapshot, unified payment)
--   3) backend/migrations/*.sql (admins, AI/outcome columns, indexes; CONCURRENT
--      index variants below use non-CONCURRENT form for transaction-safe runs)
--
-- Conventions (per migration plan):
--   - public.users.id is UUID and REFERENCES auth.users(id) ON DELETE CASCADE
--   - All former INTEGER user_id foreign keys are UUID, matching public.users
--   - RLS: intentionally NOT enabled — access enforced server-side with service role
--   - JSONB columns as in models: intelligence_snapshot_json, corrected_claim_json,
--     resubmission_package_json. batch_appeal_jobs.summary_rows uses json (JSON in SQLAlchemy)
--
-- Data migration (legacy int user ids → uuid) is a separate one-time script, not
-- this DDL file.
-- =============================================================================

-- Extensions commonly available on Supabase (for future uuid defaults if needed)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- referral_partners (created before users: users.referred_by_id references it)
-- -----------------------------------------------------------------------------
CREATE TABLE public.referral_partners (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(64) NOT NULL,
    name character varying(255) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE UNIQUE INDEX referral_partners_code_key ON public.referral_partners USING btree (code);

-- -----------------------------------------------------------------------------
-- users — id = auth.users id (Supabase Auth)
-- -----------------------------------------------------------------------------
CREATE TABLE public.users (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    email character varying(255) NOT NULL,
    stripe_customer_id character varying(255) UNIQUE,
    stripe_subscription_id character varying(255),
    subscription_tier character varying(50),
    is_paid boolean,
    payment_verification_status character varying(32),
    subscription_credits integer NOT NULL DEFAULT 0,
    bulk_credits integer NOT NULL DEFAULT 0,
    appeals_generated_monthly integer NOT NULL DEFAULT 0,
    appeals_generated_weekly integer NOT NULL DEFAULT 0,
    appeals_generated_today integer NOT NULL DEFAULT 0,
    last_monthly_reset date,
    last_weekly_reset date,
    last_daily_reset date,
    plan_limit integer NOT NULL DEFAULT 0,
    overage_count integer NOT NULL DEFAULT 0,
    billing_status character varying(50) DEFAULT 'active',
    created_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    password_hash character varying(255),
    last_queue_visit_at timestamp without time zone,
    last_active_at timestamp without time zone,
    email_retention_opt_in boolean NOT NULL DEFAULT true,
    free_trial_generations_used integer NOT NULL DEFAULT 0,
    referred_by_id integer REFERENCES public.referral_partners (id),
    provider_name character varying(200),
    provider_npi character varying(20),
    provider_address character varying(500),
    provider_phone character varying(50),
    provider_fax character varying(50)
);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);
CREATE INDEX ix_users_stripe_subscription_id ON public.users USING btree (stripe_subscription_id);
CREATE INDEX ix_users_referred_by_id ON public.users USING btree (referred_by_id);

COMMENT ON TABLE public.users IS 'Application profile; id matches auth.users id';

-- -----------------------------------------------------------------------------
-- subscription_plans, credit_packs
-- -----------------------------------------------------------------------------
CREATE TABLE public.subscription_plans (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL,
    monthly_price numeric(10, 2) NOT NULL,
    included_credits integer NOT NULL,
    overage_price numeric(10, 2) NOT NULL,
    stripe_price_id character varying(255) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE UNIQUE INDEX subscription_plans_name_key ON public.subscription_plans USING btree (name);
CREATE UNIQUE INDEX subscription_plans_stripe_price_id_key ON public.subscription_plans USING btree (stripe_price_id);

CREATE TABLE public.credit_packs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL,
    credits integer NOT NULL,
    price numeric(10, 2) NOT NULL,
    stripe_price_id character varying(255) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE UNIQUE INDEX credit_packs_stripe_price_id_key ON public.credit_packs USING btree (stripe_price_id);

-- -----------------------------------------------------------------------------
-- Idempotency & payments (unified payment / webhooks)
-- -----------------------------------------------------------------------------
CREATE TABLE public.processed_sessions (
    session_id character varying(255) NOT NULL PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    processed_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX ix_processed_sessions_user_id ON public.processed_sessions USING btree (user_id);

CREATE TABLE public.payment_transactions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id character varying(255) NOT NULL UNIQUE,
    user_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    amount numeric(12, 2),
    status character varying(64) NOT NULL DEFAULT 'succeeded',
    created_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX ix_payment_transactions_user_id ON public.payment_transactions USING btree (user_id);

CREATE TABLE public.processed_webhook_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id character varying(255) NOT NULL UNIQUE,
    event_type character varying(100) NOT NULL,
    processed_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

-- -----------------------------------------------------------------------------
-- admins (from add_admin_table.sql + models)
-- -----------------------------------------------------------------------------
CREATE TABLE public.admins (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    last_login timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE UNIQUE INDEX admins_username_key ON public.admins USING btree (username);
CREATE UNIQUE INDEX admins_email_key ON public.admins USING btree (email);
CREATE INDEX idx_admins_is_active ON public.admins USING btree (is_active);

COMMENT ON TABLE public.admins IS 'Admin users with authentication for dashboard access';

-- -----------------------------------------------------------------------------
-- appeals (models + migrate_denial_queue + migrate_tracking_columns +
-- migrate_intelligence_snapshot as JSONB + migrate_claim_recovery as JSONB +
-- add_ai_quality_and_outcome_tracking)
-- -----------------------------------------------------------------------------
CREATE TABLE public.appeals (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appeal_id character varying(50) NOT NULL,
    user_id uuid REFERENCES public.users (id) ON DELETE SET NULL,
    payer character varying(200) NOT NULL,
    payer_name text,
    claim_number character varying(100) NOT NULL,
    patient_id character varying(100) NOT NULL,
    provider_name character varying(200) NOT NULL,
    provider_npi character varying(20) NOT NULL,
    date_of_service date NOT NULL,
    denial_reason text NOT NULL,
    denial_code character varying(50),
    diagnosis_code character varying(100),
    cpt_codes character varying(200),
    billed_amount numeric(10, 2) DEFAULT 0.00,
    timely_filing_deadline date,
    denial_letter_path character varying(500),
    appeal_level character varying(50) DEFAULT 'level_1',
    credit_used boolean NOT NULL DEFAULT false,
    generation_count integer NOT NULL DEFAULT 0,
    last_generated_at timestamp without time zone,
    retail_token_used boolean NOT NULL DEFAULT false,
    status character varying(50) NOT NULL DEFAULT 'pending',
    payment_status character varying(50) DEFAULT 'unpaid',
    stripe_payment_intent_id character varying(200),
    appeal_letter_path character varying(500),
    created_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    paid_at timestamp without time zone,
    completed_at timestamp without time zone,
    price_charged numeric(10, 2) NOT NULL DEFAULT 10.00,
    ai_quality_score integer,
    ai_citation_count integer,
    ai_word_count integer,
    ai_model_used character varying(50),
    ai_generation_method character varying(50),
    outcome_status character varying(50),
    outcome_date date,
    outcome_amount_recovered numeric(10, 2),
    outcome_notes text,
    outcome_updated_at timestamp without time zone,
    queue_status character varying(50) NOT NULL DEFAULT 'pending',
    queue_notes text,
    generated_letter_text text,
    appeal_tracking_status character varying(50) DEFAULT 'pending',
    tracking_updated_at timestamp without time zone,
    payer_fax character varying(50),
    appeal_generation_kind character varying(20) DEFAULT 'initial',
    submitted_to_payer_at timestamp without time zone,
    prior_submission_date date,
    intelligence_snapshot_json jsonb,
    denial_prediction_score integer,
    fix_status character varying(32) DEFAULT 'none',
    resubmission_ready boolean NOT NULL DEFAULT false,
    corrected_claim_json jsonb,
    resubmission_package_json jsonb
);

CREATE UNIQUE INDEX appeals_appeal_id_key ON public.appeals USING btree (appeal_id);
CREATE INDEX ix_appeals_claim_number ON public.appeals USING btree (claim_number);
CREATE INDEX ix_appeals_user_id ON public.appeals USING btree (user_id);
CREATE INDEX idx_appeals_created_at_desc ON public.appeals USING btree (created_at DESC);
CREATE INDEX ix_appeals_appeal_tracking_status ON public.appeals USING btree (appeal_tracking_status);
CREATE INDEX idx_appeals_submitted_to_payer_at ON public.appeals USING btree (submitted_to_payer_at);
CREATE INDEX idx_appeals_outcome_status ON public.appeals USING btree (outcome_status);
CREATE INDEX idx_appeals_outcome_date ON public.appeals USING btree (outcome_date);
-- Reconciled from add_idx_appeals_queue_cover.sql (non-CONCURRENT for transaction safety)
CREATE INDEX IF NOT EXISTS idx_appeals_queue_cover ON public.appeals
    USING btree (created_at DESC)
    INCLUDE (id, payer, claim_number, status);

COMMENT ON COLUMN public.appeals.ai_quality_score IS 'Automated quality score (0-100) from validation system';
COMMENT ON COLUMN public.appeals.ai_citation_count IS 'Number of regulatory/clinical citations in generated appeal';
COMMENT ON COLUMN public.appeals.ai_word_count IS 'Word count of generated appeal content';
COMMENT ON COLUMN public.appeals.ai_model_used IS 'OpenAI model used (e.g., gpt-4-turbo-preview)';
COMMENT ON COLUMN public.appeals.ai_generation_method IS 'Generation method: chain_of_thought or direct';
COMMENT ON COLUMN public.appeals.outcome_status IS 'Final outcome: approved, partially_approved, denied, pending_review, withdrawn';
COMMENT ON COLUMN public.appeals.outcome_date IS 'Date of final outcome determination';
COMMENT ON COLUMN public.appeals.outcome_amount_recovered IS 'Dollar amount recovered if approved/partially approved';
COMMENT ON COLUMN public.appeals.outcome_notes IS 'Additional outcome details or reviewer feedback';
COMMENT ON COLUMN public.appeals.outcome_updated_at IS 'Timestamp of last outcome update';

-- -----------------------------------------------------------------------------
-- claim_status_events (migrate_denial_queue; user_id is uuid)
-- -----------------------------------------------------------------------------
CREATE TABLE public.claim_status_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appeal_db_id integer NOT NULL REFERENCES public.appeals (id) ON DELETE CASCADE,
    user_id uuid REFERENCES public.users (id) ON DELETE SET NULL,
    event_type character varying(80) NOT NULL,
    message text,
    created_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX ix_claim_status_events_appeal_db_id ON public.claim_status_events USING btree (appeal_db_id);
CREATE INDEX ix_claim_status_events_user_id ON public.claim_status_events USING btree (user_id);

-- -----------------------------------------------------------------------------
-- coding_intelligence_logs
-- -----------------------------------------------------------------------------
CREATE TABLE public.coding_intelligence_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.users (id) ON DELETE SET NULL,
    appeal_id character varying(50),
    event_type character varying(40) NOT NULL DEFAULT 'analyze',
    payload_json text NOT NULL,
    risk_level character varying(20),
    coding_issue_count integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX ix_coding_intelligence_logs_user_id ON public.coding_intelligence_logs USING btree (user_id);
CREATE INDEX ix_coding_intelligence_logs_appeal_id ON public.coding_intelligence_logs USING btree (appeal_id);
CREATE INDEX ix_coding_intelligence_logs_created_at ON public.coding_intelligence_logs USING btree (created_at);

-- -----------------------------------------------------------------------------
-- retention_email_logs (migrate_retention; user_id uuid)
-- -----------------------------------------------------------------------------
CREATE TABLE public.retention_email_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    campaign character varying(64) NOT NULL,
    sent_day date NOT NULL,
    sent_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT uq_retention_user_campaign_day UNIQUE (user_id, campaign, sent_day)
);

CREATE INDEX ix_retention_email_logs_user ON public.retention_email_logs USING btree (user_id);

-- -----------------------------------------------------------------------------
-- batch_appeal_jobs (migrate_batch_appeal_jobs: summary_rows = json in PostgreSQL)
-- -----------------------------------------------------------------------------
CREATE TABLE public.batch_appeal_jobs (
    job_id character varying(64) NOT NULL PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    status character varying(32) NOT NULL DEFAULT 'queued',
    job_kind character varying(16) NOT NULL DEFAULT 'csv',
    total integer,
    current integer,
    ok_count integer,
    error text,
    zip_path character varying(1024),
    zip_name character varying(512),
    summary_rows json,
    created_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX ix_batch_appeal_jobs_user_id ON public.batch_appeal_jobs USING btree (user_id);

-- =============================================================================
-- Optional seed (reconciled from migrate_acquisition ensure_acquisition_schema)
-- =============================================================================
INSERT INTO public.referral_partners (code, name, is_active)
SELECT 'demo', 'Demo Partner', true
WHERE NOT EXISTS (SELECT 1 FROM public.referral_partners WHERE code = 'demo');

-- =============================================================================
-- RLS: not enabled (server-side / service role only, per project rules)
-- =============================================================================

